apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-operator-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-operator-test
  template:
    metadata:
      labels:
        name: redis-operator-test
    spec:
      serviceAccountName: redis-operator-test
      containers:
        - name: redis-operator-test
          # Replace this with the built image name
          image: hub.xesv5.com/liulei02/liulei02:latest
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "redis-operator-test"
